feature: Structured Records
shrine-maiden-heavy-industries/torii-hdl pull request #6
Opened 2024-05-18 20:44 UTC by lethalbit

This PR adds the ability for creating more type-friendly `Record` types by using `Signal` to assign a type to each member, and then on construction generate the appropriate record layout.

For example:

```python
class FooRecord(Record):
  i: Signal[8, Direction.FANIN]
  o: Signal[8, Direction.FANOUT]
  oe: Signal[8, Direction.FANOUT]
```

They can then be used in any place a normal `Record` would be.

You can also nest them, and they behave properly, e.g. 
```python
class FooRecord(Record):
  i: Signal[8, Direction.FANIN]
  o: Signal[8, Direction.FANOUT]
  oe: Signal[8, Direction.FANOUT]

class BarRecord(Record):
  foo: FooRecord
  nya: Signal[1, Direction.FANIN]
```

2024-05-18 20:50 UTC, dragonmux requested changes
Only the one thing we can spot that looks out of place - with that fixed, feel free to make this not-a-draft and we'll get this merged.

2024-05-18 20:50 UTC, dragonmux commented on torii/hdl/ast.py
> +from typing            import Optional, Union, Generic, TYPE_CHECKING
If `TYPE_CHECKING` is not being used here, we suggest not importing it.

2024-05-18 20:57 UTC, dragonmux approved these changes
LGTM, feel free to mark this as ready-for-review when you're happy with it being merged.

2024-11-13 13:52 UTC, lethalbit commented
I'm not super happy with this, but it seems wanted enough, but I would still consider the API unstable and likely to change and break everything that uses it

2024-11-13 14:09 UTC, merged

2024-11-13 14:11 UTC, dragonmux commented
That's been done, we'll look at trying to improve the restriction on what can be put in the typing brackets for Signal, but this gets it usable for improving typing and Records.